[[stock]]
name = "Vanguard"
section = "Fund"
ticker = "VASGX"
account = "Assets:Investments:TD Ameritrade:Invested:Fund:VASGX"
shares = 3000

[[stock]]
name = "S&P 500"
section = "ETF"
ticker = "IVV"
account = "Assets:Investments:TD Ameritrade:Invested:ETF:IVV"
shares = 3000

[[stock]]
name = "S&P 500 High Div"
section = "ETF"
ticker = "SPHD"
account = "Assets:Investments:TD Ameritrade:Invested:ETF:SPHD"
shares = 3000
