[[report]]
name = "PY Job Expenses"
chart = "pie"
date_range = "Previous Year"
accounts = [ "Expenses:Job Expenses" ]

[[report]]
name = "PQ Expenses"
chart = "pie"
date_range = "Previous Quarter"
accounts = [ "Expenses" ]
exclude = [ "Job Expenses" ]

[[report]]
name = "PY Expenses"
chart = "pie"
date_range = "Previous Year"
accounts = [ "Expenses" ]
exclude = [ "Job Expenses", "Taxes" ]

[[report]]
name = "YTD Expenses"
chart = "pie"
date_range = "YTD"
accounts = [ "Expenses" ]

[[report]]
name = "AT Net Worth"
chart = "line"
date_range = "All Time"
date_freq = "Quarterly"
accounts = [ "Assets", "Liabilities" ]

[[report]]
name = "AT Vehicle Depreciation"
chart = "line"
date_range = "All Time"
date_freq = "Quarterly"
accounts = [ "Assets:Fixed Assets", "Expenses:Depreciation" ,"Liabilities:Loans:Auto" ]

[[report]]
name = "AT Yearly Income"
chart = "bar"
date_range = "All Time"
date_freq = "Yearly"
accounts = [ "Income" ]

