# .goreleaser.yml
# Build customization
builds:
  - main: ./cmd/ledger/.
    binary: ledger
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - i386
  - main: ./cmd/limport/.
    binary: limport
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - i386
  - main: ./cmd/llint/.
    binary: llint
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - i386
  - main: ./cmd/lweb/.
    binary: lweb
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - i386
archive:
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
